seekr-osint/seekr

web/css/style.css
web/js/script.js
web/lite.html

Added loading circle animation to edit and save to show the request is beeing processed, because the loading times for post person requests take a while to scan.

added loading circle anim to save btns

---

web/js/script.js

removed the 15 char max length for telephone numbers

---

api/doc.md
api/main_test.go
api/phone_type.go

phone number parsing +

---

api/doc.md
api/github_deep.go
api/main.go
api/main_test.go

added rate limit error handeling and tests

---

web/lite.html

removed unused phone number field website

---

web/js/script.js

always using the webserver url as api url

---

main.go

removed legacy web server

---

main.go

[Hotfix] Changed api port to 8569

---

default.nix
flake.lock
flake.nix
update-hash.sh

296 cicd script to auto update the vendor hash

---

web/guide.html

Changed IP field country from US to WW

Minor changes to guide info fields

---

README.md

Removed mermaid diagram

---

.devcontainer/devcontainer.json

300 cicd codespaces

---

api/doc.md

Changed port number in api docs

---

api/parse.go
api/sources/methodes.go
api/sources/type.go
api/types.go

sources now in subfolder

---

api/club/methodes.go
api/functions/errors.go
api/functions/useful.go
api/hobby/methodes.go
api/ip/methodes.go
api/sources/methodes.go

generics to generate merkdown

---

api/api_config_types.go
api/db.go
api/main.go

badgerdb and less verbose

---

web/css/style.css
web/js/framework.js
web/js/script.js
web/lite.html

Rendered IP field

---

web/css/settings.css
web/css/style.css
web/desktop.html
web/guide.html
web/index.html
web/js/desktop.js
web/js/guide.js
web/js/script.js
web/js/settings.js
web/js/tempmail.js
web/lite.html
web/settings.html
web/tempmail.html

Added theme selection instead of dark-mode switch

203 desktop theme selection

---

Dockerfile

fixed docker file

---

web/ts/script.ts

Added create to new typescript implementation

---

web/ts/script.ts

I do not know why, but this only happened sometimes and I dont know how it didnt happen 100% of the time,
because this code could never work...

Fix create save btn not always working

---

README.md

added key feature to readme

---

web/ts/settings.ts

Fix for weird theme issue

---

.github/ISSUE_TEMPLATE/themes.md

Issue template to suggest themes

Themes issue template

---

web/themes/berry.css

Added berry theme

---

web/themes/lavender.css

Bring back lavender theme

---

README.md

Added email to readme

---

examples/plugins/browser-port/build.sh
examples/plugins/browser-port/plugin.go
examples/plugins/subfinder/build.sh
examples/plugins/subfinder/plugin.go
seekrplugin/open.go

406 docs plugin docs

---

web/desktop.html
web/index.html
web/lite.html
web/ts/easteregg.ts

Added easter egg

---

api/api_config_types.go
api/config/config.go
api/config/types.go
api/github/github_deep.go
flake.nix
go.mod
go.sum
main.go

341 api toml config file

---

api/config/config.go
api/config/home.go
api/config/home_test.go
api/config/methodes.go
main.go

426 api windows support for config create flag

---

.github/ISSUE_TEMPLATE/lang.md

Added lang issue template

---

web/guide.html
web/index.html
web/lite.html
web/settings.html
web/ts/translate.ts

Translation now with better performance

---

web/ts/script.ts
web/ts/translate.ts

Fixed weird view bug

---

.gitignore
web/css/style.css
web/lite.html
web/translations/de.json
web/translations/en.json
web/translations/es.json
web/translations/gd.json
web/translations/it.json
web/translations/la.json
web/ts/framework.ts
web/ts/script.ts
web/ts/settings.ts
web/ts/translate.ts

460 website display ethnicity field

---

web/css/settings.css

Fixed settings theme bug

---

README.md

Add setup guide for windows unstable and improved

---

web/themes/pizza.css

Added pizza theme

---

web/themes/fish.css

Added fish theme

---

api/config_methodes.go
api/doc.md
api/main.go
api/main_test.go
web/ts/framework.ts

moved api to /api and / now redirects to /web

---

web/desktop.html
web/lite.html

517 website change page title to seekr desktop etc

---

web/css/style.css
web/index.html
web/lite.html
web/settings.html
web/ts/script.ts

Made buttons not selectable

---

web/ts/theme_loader.ts

Fixed old theme compatibility

---

api/services.go

Removed HTB Support

---

.github/ISSUE_TEMPLATE/doc.md

Issue template for docs

---

web/ts/settings.ts

Fix language display settings bug

---

web/ts/settings.ts

Remove logging of config

---

web/ts/settings.ts

Undo stupid stuff

---

README.md

Added discord banner

---

README.md

Fix discord banner

---

api/types.go
web/ts/framework.ts
web/ts/script.ts

562 website optimize dropdown further

---

api/config/doc.md
api/config/types.go
api/doc.md
api/main.go
api/parse.go
api/services/methodes.go
web/css/settings.css
web/settings.html
web/ts/settings.ts

added account scanning workers to config and settings

---

web/guide.html
web/ts/guide.ts
web/ts/hotfix.ts

Hotfix for guide

---

README.md

Add new discord banner

---

README.md

Proper discord invite

---

web/css/style.css

Fix bug not beeing able to copy text

---

README.md
web/css/guide.css
web/guide.html
web/ts/templates.ts

634 website add more links and countries to guide
